/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import connect.SimpleBlinkDetector;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JButton;
import looper.ChangeEvent;
import looper.ChangeListener;
import looper.Looper;
import looper.SelectEvent;
import looper.SelectListener;

/**
 *
 * @author VIVEK
 */
public class NewJFrame1 extends javax.swing.JFrame implements SelectListener, ChangeListener, FocusListener {

    Looper loop;
    SimpleBlinkDetector sbd;
    
    /**
     * Creates new form NewJFrame1
     */
    String s;
    public NewJFrame1(String s) {
        initComponents();
        this.s = s;
        jLabel1.setText(s);
        
        loop = new Looper();
        jButton1.setBackground(Color.red);
        loop.addIter(jButton1, this);
        loop.setChangeListener(this);
        sbd = new SimpleBlinkDetector();
        sbd.informOnBlink(loop);
        sbd.listen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(s.equals("correct")){
            jLabel1.setText("quit?");
            jButton1.setText("yes");
            s = "quit";
        }
        else if(s.equals("quit")){
            System.exit(0);
        }
        else{
            this.dispose();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    @Override
    public void onChange(ChangeEvent e) {
        JButton oldItem = (JButton)e.getOldLoopable().getObject();
        JButton newItem = (JButton)e.getNewLoopable().getObject();
        oldItem.setBackground(Color.white);
        newItem.setBackground(Color.red);
    }

    @Override
    public void onSelect(SelectEvent event) {
        JButton button = (JButton) event.getLoopable().getObject();
        button.doClick();
    }
    @Override
    public void focusGained(FocusEvent e) {
        this.sbd.listen();
    }

    @Override
    public void focusLost(FocusEvent e) {
        this.sbd.stop();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
